blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    def __str__(self):
        return "이름: " + self.site_name + ", 주소: " + self.url

    def get_absolute_url(self):
        return reverse('bookmark:detail', args=[str(self.id)])

bookmark/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import Bookmark
# Create your views here.

class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 6

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:list')
    template_name_suffix = '_create'

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = "_update"

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Confirm Delete {% endblock %}

{% block content %}
<form action="" method="post">
    {%csrf_token%}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}
Bookmark Add
{% endblock %}

{% block content %}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}

{% block content %}
{{object.site_name}}</br>
{{object.url}}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}
Bookmark List
{% endblock %}

{% block content %}
<div class="btn-group">
  <a href="{%url 'bookmark:add'%}" class="btn btn-info">Add Bookmark</a>
</div>
<p></p>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Site</th>
            <th scope="col">Url</th>
            <th scope="col">Modify</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for bookmark in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{%url 'bookmark:detail' pk=bookmark.id%}">{{bookmark.site_name}}</a></td>
                <td><a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a></td>
                <td><a href="{%url 'bookmark:update' pk=bookmark.id%}" class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{%url 'bookmark:delete' pk=bookmark.id%}" class="btn btn-danger btn-sm">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block pagination %}

{% if is_paginated %}
    <ul class = "pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'bookmark:list' %}?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
        </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        {% endif %}

        {% for object in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == forloop.counter %} disabled {% endif %}">
            <a class="page-link" href="{{request.path}}?page={{forloop.counter}}">{{forloop.counter}}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class=page-item">
                <a class="page-link" href="{%url 'bookmark:list'%}?page={{page_obj.next_page_number}}" tabindex="1">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        {% endif %}

    </ul>

{% endif %}

{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}
Bookmark Add
{% endblock %}

{% block content %}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}