blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('write', views.write),
    path('insert', views.insert),
    path('update', views.update),
    path('delete', views.delete),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
       return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic

# Create your views here.
def write(request):
    return render(request, "polls/write.html")

# write에 받은거 DB 연동
def insert(request):
    # 데이터 베이스에 입력 처리 (idx 는 Oracle의 순번과 동일)
    addq = Question(question=request.POST['question'],
                  ans1=request.POST['ans1'],
                  ans2=request.POST['ans2'],
                  ans3=request.POST['ans3'],
                  ans4=request.POST['ans4'],
                  status=request.POST['status'],
                  )
    addq.save()
    return redirect("/polls/index")

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def delete(request):
    idv = request.POST['survey_idx']
    print("survey_idx:", idv)
    # delete * from address_address where idx = idv
    # 선택한 데이터의 레코드가 삭제됨
    addq = Question.objects.delete()
    return redirect('/polls/list')

# =====================================================
# 수정 기능
def update(request):
    idv = request.POST['survey_idx']
    question = request.POST['question']
    ans1 = request.POST['ans1']
    ans2 = request.POST['ans2']
    ans3 = request.POST['ans3']
    ans4 = request.POST['ans4']
    status = request.POST['status']

    print("survey_idx:", idv)
    print("question:", question)
    print("ans1:", ans1)
    print("ans2:", ans2)
    print("ans3:", ans3)
    print("ans4:", ans4)
    print("status:", status)

    # 수정 데이터 베이스 처리(idx=id -> 값을 넣으면 수정, 없으면 auto로 생성되므로 없어도됨)
    addq = Question(question=question, ans1=ans1, ans2=ans2, ans3=ans3, ans4=ans4, status=status)

    # 데이터 레코드가 수정됨
    addq.save()

    return redirect('/survey/list')

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'polls/index.html', context)

# def detail(request, question_id):
#     # return HttpResponse("You're looking at question %s." % question_id)
#     # try:
#     #    question = Question.objects.get(pk=question_id)
#     #except Question.DoesNotExist:
#     #    raise Http404("Question does not exist")
#     #return render(request, 'polls/detail.html', {'question': question})
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     #response = HttpResponse("You're looking at the results of question %s." % question_id)
#     #return response
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try: selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question':question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{question.question_text}}</h1>
{% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
</body>
</html>

polls/templates/polls/index.html
{% extends "base.html" %}

{% block static %} Title {% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>

<h1>질문 목록</h1>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
    <input type="button" value="결과확인" onclick="#">
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block static %} result.html { % endblock % }

{% block content %}
<div id="wrap">
    <h1>{{question.question_text}}</h1>
    <table>
        <tr>
            <th>문항</th>
            <th>응답수</th>
        </tr>
        {% for choice in question.choice_set.all %}
        <tr>
        	<td>{{choice.choice_text}}</td>
            <td>{{choice.votes}} vote{{choice.votes|pluralize}}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2">
                <input type="button" value="투표하기" onclick="location='/polls'">
            </td>
        </tr>
    </table>
</div>
{% endblock %}

polls/templates/polls/survey_detail.html
{% extends "base.html" %}

{% block static %} upform.html { % endblock % }

{% block content %}
<div id="wrap">
<h1> survey 수정 </h1>
<form method="post" name="form1">

    {% csrf_token%}

  <input type="hidden" name="survey_idx" value="{{addq.survey_idx}}">
  <table>
    <tr>
        <td>질문</td>
        <td><input type="text" name="question" value="{{addq.question}}"></td>
    </tr>
    <tr>
        <td>응답1</td>
        <td><input type="text" name="ans1" value="{{addq.ans1}}"></td>
    </tr>
    <tr>
        <td>응답2</td>
        <td><input type="text" name="ans2" value="{{addq.ans2}}"></td>
    </tr>
    <tr>
        <td>응답3</td>
        <td><input type="text" name="ans3" value="{{addq.ans3}}"></td>
    </tr>
    <tr>
        <td>응답4</td>
        <td><input type="text" name="ans4" value="{{addq.ans4}}"></td>
    </tr>
    <tr>
        <td>상태</td>
        <td><input type="text" name="status" value="{{addq.status}}"></td>
    </tr>

    <tr>
        <th colspan="2"> <!--버튼 추가-->
            <input type="button" value="리스트" onclick="gourl()">
            <input type="button" value="수정" onclick="update()">
            <input type="button" value="삭제" onclick="del()">
        </th>
    </tr>
  </table>

</form>
</div>
    <script>
    //리스트로 이동
    function gourl(){
        location="/survey/list"
    }
    //삭제
    function del(){
        document.form1.action="delete";
        document.form1.submit();
    }
    //수정
    function update(){
        document.form1.action="update";
        document.form1.submit();
    }

    </script>
{% endblock %}

polls/templates/polls/write.html
{% extends "base.html" %}

{% block static %} write.html { % endblock % }

</head>

{% block content %}
<div id="wrap"><h1> write (설문 등록폼) </h1>
<form method="post" action="insert">

    {% csrf_token%}

  <table>
    <tr><td>질문</td><td><input type="text" name="question"></td></tr>
    <tr><td>응답1</td><td><input type="text" name="ans1"></td></tr>
    <tr><td>응답2</td><td><input type="text" name="ans2"></td></tr>
    <tr><td>응답3</td><td><input type="text" name="ans3"></td></tr>
    <tr><td>응답4</td><td><input type="text" name="ans4"></td></tr>
    <tr><td>상태</td><td><input type="text" name="status"></td></tr>
    <tr><input type="submit"></tr>
  </table>

</form>
</div>
{% endblock %}